/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.bln.tf.protocol;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
/**
 * 测试请求
 */
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-09-05")
public class BlnTestBeanReq implements org.apache.thrift.TBase<BlnTestBeanReq, BlnTestBeanReq._Fields>, java.io.Serializable, Cloneable, Comparable<BlnTestBeanReq> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("BlnTestBeanReq");

  private static final org.apache.thrift.protocol.TField HB_FIELD_DESC = new org.apache.thrift.protocol.TField("hb", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField S_FIELD_DESC = new org.apache.thrift.protocol.TField("s", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField I_FIELD_DESC = new org.apache.thrift.protocol.TField("i", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField LS_FIELD_DESC = new org.apache.thrift.protocol.TField("ls", org.apache.thrift.protocol.TType.LIST, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new BlnTestBeanReqStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new BlnTestBeanReqTupleSchemeFactory();

  /**
   * 头信息 (固定)
   */
  public BlnHeadBean hb; // optional
  /**
   * string
   */
  public java.lang.String s; // optional
  /**
   * int
   */
  public int i; // optional
  /**
   * list
   */
  public java.util.List<java.lang.String> ls; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 头信息 (固定)
     */
    HB((short)1, "hb"),
    /**
     * string
     */
    S((short)2, "s"),
    /**
     * int
     */
    I((short)3, "i"),
    /**
     * list
     */
    LS((short)4, "ls");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // HB
          return HB;
        case 2: // S
          return S;
        case 3: // I
          return I;
        case 4: // LS
          return LS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __I_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.HB,_Fields.S,_Fields.I,_Fields.LS};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.HB, new org.apache.thrift.meta_data.FieldMetaData("hb", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, BlnHeadBean.class)));
    tmpMap.put(_Fields.S, new org.apache.thrift.meta_data.FieldMetaData("s", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.I, new org.apache.thrift.meta_data.FieldMetaData("i", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.LS, new org.apache.thrift.meta_data.FieldMetaData("ls", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(BlnTestBeanReq.class, metaDataMap);
  }

  public BlnTestBeanReq() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public BlnTestBeanReq(BlnTestBeanReq other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetHb()) {
      this.hb = new BlnHeadBean(other.hb);
    }
    if (other.isSetS()) {
      this.s = other.s;
    }
    this.i = other.i;
    if (other.isSetLs()) {
      java.util.List<java.lang.String> __this__ls = new java.util.ArrayList<java.lang.String>(other.ls);
      this.ls = __this__ls;
    }
  }

  public BlnTestBeanReq deepCopy() {
    return new BlnTestBeanReq(this);
  }

  @Override
  public void clear() {
    this.hb = null;
    this.s = null;
    setIIsSet(false);
    this.i = 0;
    this.ls = null;
  }

  /**
   * 头信息 (固定)
   */
  public BlnHeadBean getHb() {
    return this.hb;
  }

  /**
   * 头信息 (固定)
   */
  public BlnTestBeanReq setHb(BlnHeadBean hb) {
    this.hb = hb;
    return this;
  }

  public void unsetHb() {
    this.hb = null;
  }

  /** Returns true if field hb is set (has been assigned a value) and false otherwise */
  public boolean isSetHb() {
    return this.hb != null;
  }

  public void setHbIsSet(boolean value) {
    if (!value) {
      this.hb = null;
    }
  }

  /**
   * string
   */
  public java.lang.String getS() {
    return this.s;
  }

  /**
   * string
   */
  public BlnTestBeanReq setS(java.lang.String s) {
    this.s = s;
    return this;
  }

  public void unsetS() {
    this.s = null;
  }

  /** Returns true if field s is set (has been assigned a value) and false otherwise */
  public boolean isSetS() {
    return this.s != null;
  }

  public void setSIsSet(boolean value) {
    if (!value) {
      this.s = null;
    }
  }

  /**
   * int
   */
  public int getI() {
    return this.i;
  }

  /**
   * int
   */
  public BlnTestBeanReq setI(int i) {
    this.i = i;
    setIIsSet(true);
    return this;
  }

  public void unsetI() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __I_ISSET_ID);
  }

  /** Returns true if field i is set (has been assigned a value) and false otherwise */
  public boolean isSetI() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __I_ISSET_ID);
  }

  public void setIIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __I_ISSET_ID, value);
  }

  public int getLsSize() {
    return (this.ls == null) ? 0 : this.ls.size();
  }

  public java.util.Iterator<java.lang.String> getLsIterator() {
    return (this.ls == null) ? null : this.ls.iterator();
  }

  public void addToLs(java.lang.String elem) {
    if (this.ls == null) {
      this.ls = new java.util.ArrayList<java.lang.String>();
    }
    this.ls.add(elem);
  }

  /**
   * list
   */
  public java.util.List<java.lang.String> getLs() {
    return this.ls;
  }

  /**
   * list
   */
  public BlnTestBeanReq setLs(java.util.List<java.lang.String> ls) {
    this.ls = ls;
    return this;
  }

  public void unsetLs() {
    this.ls = null;
  }

  /** Returns true if field ls is set (has been assigned a value) and false otherwise */
  public boolean isSetLs() {
    return this.ls != null;
  }

  public void setLsIsSet(boolean value) {
    if (!value) {
      this.ls = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case HB:
      if (value == null) {
        unsetHb();
      } else {
        setHb((BlnHeadBean)value);
      }
      break;

    case S:
      if (value == null) {
        unsetS();
      } else {
        setS((java.lang.String)value);
      }
      break;

    case I:
      if (value == null) {
        unsetI();
      } else {
        setI((java.lang.Integer)value);
      }
      break;

    case LS:
      if (value == null) {
        unsetLs();
      } else {
        setLs((java.util.List<java.lang.String>)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case HB:
      return getHb();

    case S:
      return getS();

    case I:
      return getI();

    case LS:
      return getLs();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case HB:
      return isSetHb();
    case S:
      return isSetS();
    case I:
      return isSetI();
    case LS:
      return isSetLs();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof BlnTestBeanReq)
      return this.equals((BlnTestBeanReq)that);
    return false;
  }

  public boolean equals(BlnTestBeanReq that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_hb = true && this.isSetHb();
    boolean that_present_hb = true && that.isSetHb();
    if (this_present_hb || that_present_hb) {
      if (!(this_present_hb && that_present_hb))
        return false;
      if (!this.hb.equals(that.hb))
        return false;
    }

    boolean this_present_s = true && this.isSetS();
    boolean that_present_s = true && that.isSetS();
    if (this_present_s || that_present_s) {
      if (!(this_present_s && that_present_s))
        return false;
      if (!this.s.equals(that.s))
        return false;
    }

    boolean this_present_i = true && this.isSetI();
    boolean that_present_i = true && that.isSetI();
    if (this_present_i || that_present_i) {
      if (!(this_present_i && that_present_i))
        return false;
      if (this.i != that.i)
        return false;
    }

    boolean this_present_ls = true && this.isSetLs();
    boolean that_present_ls = true && that.isSetLs();
    if (this_present_ls || that_present_ls) {
      if (!(this_present_ls && that_present_ls))
        return false;
      if (!this.ls.equals(that.ls))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetHb()) ? 131071 : 524287);
    if (isSetHb())
      hashCode = hashCode * 8191 + hb.hashCode();

    hashCode = hashCode * 8191 + ((isSetS()) ? 131071 : 524287);
    if (isSetS())
      hashCode = hashCode * 8191 + s.hashCode();

    hashCode = hashCode * 8191 + ((isSetI()) ? 131071 : 524287);
    if (isSetI())
      hashCode = hashCode * 8191 + i;

    hashCode = hashCode * 8191 + ((isSetLs()) ? 131071 : 524287);
    if (isSetLs())
      hashCode = hashCode * 8191 + ls.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(BlnTestBeanReq other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetHb()).compareTo(other.isSetHb());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHb()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.hb, other.hb);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetS()).compareTo(other.isSetS());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetS()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.s, other.s);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetI()).compareTo(other.isSetI());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetI()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.i, other.i);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetLs()).compareTo(other.isSetLs());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLs()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ls, other.ls);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("BlnTestBeanReq(");
    boolean first = true;

    if (isSetHb()) {
      sb.append("hb:");
      if (this.hb == null) {
        sb.append("null");
      } else {
        sb.append(this.hb);
      }
      first = false;
    }
    if (isSetS()) {
      if (!first) sb.append(", ");
      sb.append("s:");
      if (this.s == null) {
        sb.append("null");
      } else {
        sb.append(this.s);
      }
      first = false;
    }
    if (isSetI()) {
      if (!first) sb.append(", ");
      sb.append("i:");
      sb.append(this.i);
      first = false;
    }
    if (isSetLs()) {
      if (!first) sb.append(", ");
      sb.append("ls:");
      if (this.ls == null) {
        sb.append("null");
      } else {
        sb.append(this.ls);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (hb != null) {
      hb.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class BlnTestBeanReqStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public BlnTestBeanReqStandardScheme getScheme() {
      return new BlnTestBeanReqStandardScheme();
    }
  }

  private static class BlnTestBeanReqStandardScheme extends org.apache.thrift.scheme.StandardScheme<BlnTestBeanReq> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, BlnTestBeanReq struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // HB
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.hb = new BlnHeadBean();
              struct.hb.read(iprot);
              struct.setHbIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // S
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.s = iprot.readString();
              struct.setSIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // I
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.i = iprot.readI32();
              struct.setIIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // LS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list10 = iprot.readListBegin();
                struct.ls = new java.util.ArrayList<java.lang.String>(_list10.size);
                java.lang.String _elem11;
                for (int _i12 = 0; _i12 < _list10.size; ++_i12)
                {
                  _elem11 = iprot.readString();
                  struct.ls.add(_elem11);
                }
                iprot.readListEnd();
              }
              struct.setLsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, BlnTestBeanReq struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.hb != null) {
        if (struct.isSetHb()) {
          oprot.writeFieldBegin(HB_FIELD_DESC);
          struct.hb.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      if (struct.s != null) {
        if (struct.isSetS()) {
          oprot.writeFieldBegin(S_FIELD_DESC);
          oprot.writeString(struct.s);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetI()) {
        oprot.writeFieldBegin(I_FIELD_DESC);
        oprot.writeI32(struct.i);
        oprot.writeFieldEnd();
      }
      if (struct.ls != null) {
        if (struct.isSetLs()) {
          oprot.writeFieldBegin(LS_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.ls.size()));
            for (java.lang.String _iter13 : struct.ls)
            {
              oprot.writeString(_iter13);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class BlnTestBeanReqTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public BlnTestBeanReqTupleScheme getScheme() {
      return new BlnTestBeanReqTupleScheme();
    }
  }

  private static class BlnTestBeanReqTupleScheme extends org.apache.thrift.scheme.TupleScheme<BlnTestBeanReq> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, BlnTestBeanReq struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetHb()) {
        optionals.set(0);
      }
      if (struct.isSetS()) {
        optionals.set(1);
      }
      if (struct.isSetI()) {
        optionals.set(2);
      }
      if (struct.isSetLs()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetHb()) {
        struct.hb.write(oprot);
      }
      if (struct.isSetS()) {
        oprot.writeString(struct.s);
      }
      if (struct.isSetI()) {
        oprot.writeI32(struct.i);
      }
      if (struct.isSetLs()) {
        {
          oprot.writeI32(struct.ls.size());
          for (java.lang.String _iter14 : struct.ls)
          {
            oprot.writeString(_iter14);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, BlnTestBeanReq struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.hb = new BlnHeadBean();
        struct.hb.read(iprot);
        struct.setHbIsSet(true);
      }
      if (incoming.get(1)) {
        struct.s = iprot.readString();
        struct.setSIsSet(true);
      }
      if (incoming.get(2)) {
        struct.i = iprot.readI32();
        struct.setIIsSet(true);
      }
      if (incoming.get(3)) {
        {
          org.apache.thrift.protocol.TList _list15 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.ls = new java.util.ArrayList<java.lang.String>(_list15.size);
          java.lang.String _elem16;
          for (int _i17 = 0; _i17 < _list15.size; ++_i17)
          {
            _elem16 = iprot.readString();
            struct.ls.add(_elem16);
          }
        }
        struct.setLsIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

